### PR TITLE
Revert "Upgraded OpenCV to version 3.4.2."

### PR DESCRIPTION
**Pull request by eggerk**
Reverts ethz-asl/opencv3_catkin#20

breaks vision_opencv

### CODE REVIEW

**Comment by ffurrer** [comment]
Can you elaborate on this?

**Comment by eggerk** [comment]
@ffurrer: OpenCV 3.4 changed some interface that is used in vision_opencv, making it fail: https://jenkins.asl.ethz.ch/job/vision_opencv/22/label=ubuntu-xenial/

**Comment by ffurrer** [comment]
@eggerk Can you fix vision_opencv instead? Seems to build on OSX.

**Comment by eggerk** [comment]
@ffurrer The tests are not run on OSX: https://github.com/ethz-asl/vision_opencv/blob/kinetic/cv_bridge/CMakeLists.txt#L46
Are you using the new OpenCV version somewhere?

**Comment by ffurrer** [comment]
Yup, we switched to this version now and if we revert all our unit tests will fail again. There seem to be different ways to compute keypoints and descriptors among different versions, and we have unit tests to check for number of keypoints and matches (which are version dependent).

**Comment by eggerk** [comment]
I see, in this case we probably shouldn't revert this, but try to get vision_opencv/aslam/maplab updated to the new opencv as soon as possible too.

Are you not using vision_opencv yourself?

(@fabianbl fyi)

**Pull request closed without merging**
