### PR TITLE
Disable lapack by default

### PR DESCRIPTION
**Pull request by margaritaG**
Temporarily disable lapack to get rid of opencv 3.2.0 linking error: https://github.com/opencv/opencv/issues/7970

### CODE REVIEW

**Review by ffurrer — APPROVED** [review]
Yeah let's do this, but when updating to a newer opencv version we should remove it again, and we should update to a newer opencv version soon I guess, or is there any objection @ethz-asl/3d_developers @ethz-asl/maplab_developers ?

**Comment by fabianbl** [comment]
Do you know if updating to 3.4.1 would solve this issue? In this case, I would prefer the update. I could do this.

**Comment by margaritaG** [comment]
Already OpenCV 3.3.0 solves it, it has the necessary fix in there: https://github.com/opencv/opencv/pull/7999

**Comment by mfehr** [comment]
last time updating maplab to the new ocv was quite a lengthy and painful procedure if I remember correctly. Thanks @fabianbl for volunteering ;)

Wouldn't a better temporary fix be to apply the patch?

**Comment by fabianbl** [comment]
@mfehr Good to know ;-) Agree, a patch would maybe be more suitable here. I will have a look this afternoon.

**Comment by margaritaG** [comment]
Thank you @fabianbl, let me know if I can help

**Comment by eggerk** [comment]
@mfehr I think only the initial update from opencv2 to 3 took a lot of time. We once updated this to 3.2 which didn't cause any issues on the maplab side.

If we apply this patch, can we at least only disable lapack on 14.04? Because the other systems aren't affected so we should leave everything as is.

**Pull request closed without merging**
